version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=alem
      - DATABASE_USERNAME=postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alem
    volumes:
      - postgres-db:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment: 
        - PGADMIN_DEFAULT_EMAIL=miko_982@mail.ru
        - PGADMIN_DEFAULT_PASSWORD=admin
    ports: 
        - "5050:80"   

  token_listener:
      build: .
      volumes:
      - ./:/usr/src/app
      command: ["python","-u", "run_token_updater.py"]



volumes:
  postgres-db: